version: 2

jobs:
  build:
    docker:
      - image: docker:stable
    steps:
      - checkout
      - run: apk --update add make curl
      - setup_remote_docker:
          version: 18.09.3
      - run: docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
      - run: docker run --rm --privileged multiarch/qemu-user-static:latest --reset
      - run: echo ".git" > .dockerignore
      - run: make -j$(nproc --all) prepare-old
      - run: make -j$(nproc --all) build-push
      - run: make -j$(nproc --all) test ping

workflows:
  version: 2
  builder:
    jobs:
      - build
  nightly:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - build
